# set :domain, 'XX.XX.XXX.XXX'
# set :deploy_to, '/home/deploy/apps/eightbit-standup-rails-staging'
# set :repository, 'git@github.com:jameswilliamiii/eightbit_standup_rails.git'
# set :branch, 'staging'
# set :user, 'deploy'
# set :forward_agent, true
# set :unicorn_pid, "#{deploy_to}/shared/pids/unicorn.pid"
# set :rails_env, 'staging'
# set :unicorn_env, "staging"
